rewrite GPT parsing (#92)

diff --git a/.github/workflows/hitl.yml b/.github/workflows/hitl.yml
--- a/.github/workflows/hitl.yml
+++ b/.github/workflows/hitl.yml
@@ -39,6 +39,44 @@ jobs:
 
       - run: qdl.js flash boot_a ./boot.img
 
+  test-activeslot:
+    name: Test getting and setting active slot
+    runs-on: [self-hosted, Linux, HITL]
+    timeout-minutes: 1
+    steps:
+      - uses: actions/checkout@v4
+      - uses: ./.github/workflows/prepare-cli
+
+      - run: qdl.js setactiveslot a
+
+      - name: verify slot is a
+        run: |
+          NEW_SLOT=$(qdl.js getactiveslot)
+          echo "New active slot: $NEW_SLOT"
+          if [ "$NEW_SLOT" != "a" ]; then
+            echo "ERROR: Slot did not change!"
+            exit 1
+          fi
+        env:
+          QDL_LOG_LEVEL: error
+
+      - run: qdl.js printgpt
+
+      - run: qdl.js setactiveslot b
+
+      - name: verify slot is b
+        run: |
+          NEW_SLOT=$(qdl.js getactiveslot)
+          echo "New active slot: $NEW_SLOT"
+          if [ "$NEW_SLOT" != "b" ]; then
+            echo "ERROR: Slot did not change!"
+            exit 1
+          fi
+        env:
+          QDL_LOG_LEVEL: error
+
+      - run: qdl.js printgpt
+
   test-repairgpt:
     name: Test GPT repair functionality
     runs-on: [self-hosted, Linux, HITL]
@@ -55,14 +93,10 @@ jobs:
             curl -L $url | unxz > gpt_main_$i.img
           done
 
-      - run: qdl.js printgpt --backup
-
       - run: |
           END=5
           for i in $(seq 0 $END); do
             qdl.js repairgpt $i ./gpt_main_$i.img
           done
 
-      - run: qdl.js printgpt --backup
-
-      - run: qdl.js getactiveslot
+      - run: qdl.js printgpt
